from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.types import Command

from src.state import AgentState
from src.utils.llm import get_llm
from src.tools.verification_tools import tools

def agent_node(state: AgentState):
    """The central agent node that reasons and calls tools."""
    print("--- New Messages for Agent ---")
    new_msgs = []
    for msg in reversed(state["messages"]):
        if msg.__class__.__name__ == "AIMessage":
            break
        new_msgs.insert(0, msg)
        
    for msg in new_msgs:
        print(f"\n[{msg.__class__.__name__}]:\n{msg.content}\n")
    print("--- AGENT REASONING ---")
    
    llm = get_llm()
    # Bind tools to the LLM
    llm_with_tools = llm.bind_tools(tools)
    
    # Construct System Prompt
    system_prompt = f"""You are an expert autonomous hardware verification agent.
Your goal is to test the given SystemVerilog Design Under Test (DUT) using a hybrid approach. You will write two seperate piceces of code, a driver (in systemverilog) that drives the dut and stores the stimulus and responses to a csv file, and a checker (in python) that models the expected behavior of the dut and verifies the actual outputs from the csv file against the expected outputs for each input.

Test Plan:

1. First analyze the dut description and create a structured plan using the task manager tool to keep track of your progress. 

2. You must use a hybrid testbench strategy with a driver (in systemverilog) and a checker (in python). 

3. Create a system verilog testbench that instantiates the DUT and drives stimuli to it and stores all the inputs+outputs in a csv file called "driver_output.csv". 

4. Create a standalone checker in python that models the expected behavior of the dut based on the specifications, and that parses the csv file generated by the driver and verifies the DUT by comparing the actual outputs with the expected outputs for each input.

Available Skills:
{state.get('skills_summary', 'None')}

DUT Description and Headers (DUT is generated with the following prompt by an LLM):
{state.get('dut_description', 'N/A')}
"""

    messages = [SystemMessage(content=system_prompt)] + state["messages"]
    
    response = llm_with_tools.invoke(messages)

    if hasattr(response, "tool_calls") and response.tool_calls:
        tool_names = [tc["name"] for tc in response.tool_calls]
        print(f"\n[AGENT DECISION] Tool Calls: {', '.join(tool_names)}\n")
    else:
        print("\n[AGENT DECISION] AI responded without using tools.\n")
    
    # Check for empty response or malformed function calls (common with large code payloads)
    finish_reason = response.response_metadata.get('finish_reason', '')
    if finish_reason == 'MALFORMED_FUNCTION_CALL' or (not response.content and not getattr(response, "tool_calls", None)):
        print("         [WARNING]: LLM returned a malformed function call. Retrying...")
        retry_msg = HumanMessage(content="Your last function call was malformed JSON (likely due to unescaped quotes in the code). Please try again and ensure the JSON arguments are valid.")
        return Command(goto="agent", update={"messages": [response, retry_msg]})
        
    # We return the newly generated message to be appended to the state
    return {"messages": [response]}